### ISSUE TITLE
running on non-UCL system

### ISSUE THREAD

**Issue by rob123king** [UCL-BLIC/DGE#1]
Just looking how to adapt this to our system. If I install GSEA and R/deseq2 on our system and load before I can just use profile=local or would I need to create a config for that? Having tools in path is not that difficult so hoping that will just get it to run. I'm still trying to figure our nextflow. I've run the rnaseq tool on aws using tower and working on getting it on our system. Then looking to follow up with this.

**Comment by rob123king** [comment]
I'm having this issue but the tool is installed. I'll have a look if can change the code. looks like the --log parameter is not recognised.

Caused by:
  Process `preprocess_illumina:sortmerna (2)` terminated with an error exit status (1)

Command executed:

  unpigz -f -p 1 MAQCB_rep2.trimmed.fastq.gz
  sortmerna --ref ./rRNA_databases/silva-bac-16s-id90.fasta,./rRNA_databases/silva-bac-16s-id90:./rRNA_databases/silva-bac-23s-id98.fasta,./rRNA_databases/silva-bac-23s-id98:./rRNA_databases/silva-arc-16s-id95.fasta,./rRNA_databases/silva-arc-16s-id95:./rRNA_databases/silva-arc-23s-id98.fasta,./rRNA_databases/silva-arc-23s-id98:./rRNA_databases/silva-euk-18s-id95.fasta,./rRNA_databases/silva-euk-18s-id95:./rRNA_databases/silva-euk-28s-id98.fasta,./rRNA_databases/silva-euk-28s-id98:./rRNA_databases/rfam-5s-database-id98.fasta,./rRNA_databases/rfam-5s-database-id98:./rRNA_databases/rfam-5.8s-database-id98.fasta,./rRNA_databases/rfam-5.8s-database-id98     --reads MAQCB_rep2.trimmed.fastq     --aligned MAQCB_rep2.aligned     --other MAQCB_rep2.other     --fastx --log --num_alignments 1 -v     -a 1
  pigz -p 1 MAQCB_rep2.other.fastq
  rm MAQCB_rep2.aligned.fastq MAQCB_rep2.trimmed.fastq

Command exit status:
  1

ommand error:
  
  [opt_default:943] [0;31mERROR[0m: Option: 'log' is not recognized

**Comment by rob123king** [comment]
I think just have an old version of SortMeRNA, I'll try updating

**Comment by lconde-ucl** [comment]
Hi @rob123king, you don't need a config file to run the DGE pipeline, as long as you have all the software in the path and point to the genesets (--gmx parameter) and to the --txt2gene file then it should run. You will have to change the path the gsea in the /bin/run_gsea.pl script though, as it is hardcoded there.
If you are running an rnaseq pipeline to follow up with this DGE one, I suggest you use the [nfcore-rnaseq](https://github.com/nf-core/rnaseq) pipeline.
