### ISSUE TITLE
Running on other systems

### ISSUE THREAD

**Issue by aforsythe** [UCL-BLIC/DGE#4]
Just a feature request ... rather than ask users to install various R packages, why not create a singularity container with R and the necessary packages?

**Comment by lconde-ucl** [comment]
Hi @aforsythe, thanks for your interest. Yes, ideally we would upgrade it to DSL2 and containerise it, but unfortunately I don't foresee this happening in the near future.

To be honest, this pipeline was originally developed for internal use. Users from UCL don't have to install anything, they just need to load a module. If someone from an external institution wishes to utilise it, the source code is public, but they will need to manage a few prerequisites, such as having the required packages installed. 

An external user submitted a PR to include some guidance for non-UCL users in the documentation, but I agree that the optimal approach for external users would involve containerisation. We might consider doing this in the future, but I'm afraid that upgrading this pipeline is not something we are prioritising at the moment.

**Comment by colindaven** [comment]
Perhaps https://github.com/nf-core/differentialabundance is a recent and suitable pipeline for those wanting a solution in DSL2 which includes containers ?

**Comment by lconde-ucl** [comment]
Hi @colindaven, absolutely! It took a while, I remember discussing the development of a DGE pipeline in [this issue](https://github.com/nf-core/rnaseq/issues/409) back in 2020!
But it's great to see that there's now one available at nf-core. I highly recommend opting for that option, as it will receive ongoing development and more consistent maintenance compared to this one.

**Comment by aforsythe** [comment]
Thank you both.  This seems like it will work for my purposes.  

Stupid question, but does [differentialabundance](https://github.com/nf-core/differentialabundance) spit out a heat map of genes across samples?  After a quick look, I didn't see that, but maybe I just missed it.

**Comment by lconde-ucl** [comment]
I don't know for sure because I haven't used it myself. However, after taking a very quick look at [this](https://github.com/nf-core/differentialabundance/blob/master/modules/nf-core/shinyngs/staticexploratory/main.nf) and [this](https://github.com/nf-core/differentialabundance/blob/master/modules/nf-core/shinyngs/staticexploratory/main.nf) modules, it appears that there are outputs for volcano, sample dendrogram, PCA, and others plots, but I don't see a heatmap there. I'm guessing you might need to check the output for text files that could be used to generate the heatmap.

However, to be sure it will be better if you reach out to the developers directly

**Comment by aforsythe** [comment]
Totally understand and greatly appreciate the help!

**Comment by lconde-ucl** [comment]
Hi @aforsythe @colindaven 

Just to let you know that I finally moved this pipeline to DSL2 and can now be executed as any other nf-core pipeline with docker/singularity, e.g.:

`
nextflow run lconde-ucl/DGE2 -profile test,singularity --outdir results_dge
`

I still recommend to use the [differentialabundance](https://github.com/nf-core/differentialabundance) as it's supported by nf-core, but if for whatever reason you still want to run this one, the newer version is available at [lconde-ucl/DGE2](https://github.com/lconde-ucl/DGE)

Best
Lucia

**Comment by colindaven** [comment]
Hi Lucia,

great, thanks very much for letting me know. Please don't delete this pipeline since I still sometimes run analyses based on this.

Best wishes,
Colin

**Comment by lconde-ucl** [comment]
@colindaven Yes, no worries, I'll keep both versions here
Best
Lucia
